/* Copyright (C) 2002, The IPDR Organization, all rights reserved.
* The use and distribution of this software is governed by the terms of
* the license agreement which can be found in the file LICENSE.TXT at
* the top of this source tree.
*
* This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF
* ANY KIND, either express or implied.
*/



/*List of mnemonics for Error Codes*/

#ifndef _ERRORCODE_H
#define _ERRORCODE_H

#include <stdio.h>

/* Error Severity*/
#define IPDR_OK						                0
#define IPDR_WARNING								1
#define IPDR_ERROR                                  2

/* Error Code*/
#define IPDR_UNKNOWN_NS_PREFIX						3
#define IPDR_NO_SD_FILE								4
#define IPDR_INVALID_SD_FILE						5
#define IPDR_NO_SD_URI								6
#define IPDR_NULL_UUID								7
#define IPDR_NULL_TIME								9
#define IPDR_INVALID_TIME_FORMAT					11
#define IPDR_INVALID_DOCTYPE						12
#define IPDR_INVALID_STREAM_HANDLE					13
#define IPDR_UNREADABLE_ISTREAM						14
#define IPDR_UNWRITABLE_OSTREAM						15
#define IPDR_INVALID_DOCSTATE_MAKE_READABLE			16
#define IPDR_INVALID_DOCSTATE_MAKE_UNREADABLE		17
#define IPDR_INVALID_DOCSTATE_MAKE_WRITABLE			18
#define IPDR_INVALID_DOCSTATE_MAKE_UNWRITABLE		19
#define IPDR_NULL_INPUT_PARAMETER					20
#define IPDR_MISMATCH_NS_SD							21
#define IPDR_LESS_SD_THAN_NS						22
#define IPDR_NON_PRIMITIVE_DATA_TYPE				23
#define IPDR_MISMATCH_DESCRIPTOR_DATA_ARRAY			24
#define IPDR_MISMATCH_ATTRIBUTE_DATA_ARRAY			25
#define IPDR_NO_SCHEMA								26
#define IPDR_NO_DESCID								27
#define IPDR_INVALID_DESCRIMINATOR					28
#define IPDR_INVALID_VERSION						29
#define IPDR_INVALID_IPV4ADDR						30
#define IPDR_INVALID_IPV6ADDR						31
#define IPDR_MISMATCH_XML_TAGS						32
#define IPDR_NO_DOCEND								33
#define IPDR_INVALID_FILE							34
#define IPDR_INVALID_OBJECT							35
#define IPDR_INVALID_URL							36
#define IPDR_INVALID_LOGIN							37
#define IPDR_NO_SUCH_FILE							39
#define IPDR_INVALID_COMPACT_FORMAT					40
#define IPDR_CONNECTION_FAILED						42
#define IPDR_PARSING_ERROR							43
#define IPDR_MISMATCH_OPTIONAL_ATTRNAME_SCHEMA		44
#define IPDR_MISMATCH_INPUT_DATA_SCHEMA_LOOKUP		45
#define IPDR_INVALID_LENGTH_SD						46
#define IPDR_INVALID_LENGTH_SD_NO_DFLT_NS			47
#define IPDR_DUPLICATE_ATTRIBUTE_NAME				48
#define IPDR_NULL_INPUT_DATA						49
#define IPDR_NO_SUCH_DESCRIPTOR						50
#define IPDR_MANDATORY_ATTR_NOT_FOUND				51
#define IPDR_MISMATCH_INPUT_WITH_SCHEMA_DATATYPE	52 
#define IPDR_NO_SUCH_ATTRIBUTE_IN_SCHEMA			53
#define IPDR_EOF_ENCOUNTERED						54
#define IPDR_EOF_NOT_FOUND_IN_IPDRDOC				55
#define IPDR_MISMATCH_IN_ENCODED_DECODED_RECORDS	56
#define IPDR_MISMATCH_ATTRTAGS_IPDRDOC_SCHEMA		57
#define IPDR_DUPLICATE_DESCID						58
#define IPDR_INVALID_DOCTYPE_MAKE_XML				59
#define IPDR_INVALID_SCHEMA							60
#define IPDR_MEMORY_ALLOCATION_FAILED				61
#define IPDR_NO_MANADATORY_PARAMS					62
#define IPDR_NO_HYPHEN_AND_EQUAL					63
#define IPDR_LESS_THAN_TWO_FILES_FOR_RR				64
#define IPDR_INVALID_INPUT_PARAM_NAME				65
#define IPDR_INVALID_INPUT_PARAM_VALUE				66
#define IPDR_BLANK_ATTRIBUTE						67
#define IPDR_INVALID_UUID							68
#define IPDR_INVALID_DELIMITER_FOR_ADDR_STRING		69
#define IPDR_NO_DELIMITER_FOR_ADDR_STRING		    70
#define IPDR_INVALID_DIGIT_FOR_ADDR_STRING		    71
#define IPDR_INVALID_LENGTH_OF_BLOCK_FOR_ADDR_STRING 72
#define IPDR_INVALID_VALUE_OF_BLOCK_FOR_ADDR_STRING  73
#define IPDR_INVALID_LENGTH_OF_ADDR_STRING			 74
#define IPDR_NULL_LINKLIST							 75
#define IPDR_INVALID_YEAR_IN_TIME_FORMAT			 76
#define IPDR_INVALID_MONTH_IN_TIME_FORMAT			 77
#define IPDR_INVALID_DAYS_IN_TIME_FORMAT			 78
#define IPDR_INVALID_HOURS_IN_TIME_FORMAT			 79
#define IPDR_INVALID_MIN_IN_TIME_FORMAT			 	 80
#define IPDR_INVALID_SEC_IN_TIME_FORMAT			 	 81
#define IPDR_SUBSCRIPT_OUT_OF_RANGE					 82
#define IPDR_INVALID_RECORDCOUNT					 83
#define IPDR_MISSING_OR_INVALID_COMMANDLINE_PARAMS	 84	
#define IPDR_MISSING_OR_INVALID_OUTFILE              85

//IPDR v3.5, version changes
#define IPDR_USER_AND_SCHEMA_VERSION_MISMATCH_ERROR  137
#define IPDR_NO_DATA_IN_FILE								  138

/* Schema Errors*/
#define IPDR_MISMATCH_NS_DFLT_NS                     86
#define IPDR_ST_FOR_SCHEMA_ABSENT                    87
#define IPDR_MISMATCH_TRGT_NS_ONS                    88
#define IPDR_MISMATCH_TRGT_NS_DFLT_NS                89 
#define IPDR_DATATYPE_MISMATCH_IN_SCHEMA_AND_FNFDATA 90
#define IPDR_MACTH_ONS_DNS							 91 	
#define IPDR_NULL_KEY_VALUE                          92
#define IPDR_NULL_SCHEMA_LOOKUP                      93
#define IPDR_NULL_DATA_VALUE						 94
#define IPDR_HASHGET_NULL                            102
#define IPDR_GETID_NULL                              103  
#define IPDR_GETNAME_NULL                            116 
#define IPDR_KEYTOK_FAIL                             117 
#define IPDR_GETURI_NULL                             118  

/* LIBCURL ERRORS */
#define IPDR_CURLE_COULDNT_CONNECT					95
#define IPDR_CURLE_FTP_COULDNT_RETR_FILE			96
#define IPDR_CURLE_FTP_ACCESS_DENIED				97
#define IPDR_CURLE_LOCAL_FILENAME_NULL				98
#define IPDR_CURLE_LOCAL_FILENAME_BLANK				99
#define IPDR_CURLE_WRITE_ERROR						100
#define IPDR_CURLE_GENERAL_ERROR					101

/* DESCRIPTOR ERRORS */
#define IPDR_DESCRIPTOR_SCHEMA_FILE_NULL			104
#define IPDR_DESCRIPTOR_SCHEMA_FILE_INVALID			105
#define IPDR_DESCRIPTOR_PARSER_MEMORY_ALLOC_FAILED	106
#define IPDR_DESCRIPTOR_FILE_NOT_FOUND				107
#define IPDR_DESCRIPTOR_READ_ERROR					108
#define IPDR_DESCRIPTOR_PARSER_READ_ERROR			109
#define IPDR_DESCRIPTOR_SCHEMA_FILE_NOT_FOUND       110

/* XML ERORRS */
#define IPDR_XML_INPUT_FILE_NULL					120
#define IPDR_XML_INPUT_FILE_INVALID					121
#define IPDR_XML_MEMORY_ALLOCATION_FAILED			122
#define IPDR_XML_PARSER_MEMORY_ALLOC_FAILED			123
#define IPDR_XML_READ_ERROR							124
#define IPDR_XML_PARSER_READ_ERROR					125

#define IPDR_XML_NULL_TIME							126
#define IPDR_XML_NULL_DOCID							127
#define IPDR_XML_NULL_ONS							128
#define IPDR_XML_NULL_SD							129
#define IPDR_XML_NULL_RI							130
#define IPDR_XML_NULL_DNS							131
#define IPDR_INVALID_ORDER							132

#define IPDR_LOOKUP_PARSER_MEMORY_ALLOC_FAILED                                  133
#define IPDR_LOOKUP_FILE_NOT_FOUND                                              134
#define IPDR_LOOKUP_READ_ERROR                                                  135
#define IPDR_LOOKUP_PARSER_READ_ERROR                                           136


/* Newly Added expat parser related error codes Series 200 - 299 */
#define EXPAT_ERROR_CODE							200
#define EXPAT_ERROR_NO_MEMORY						1 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_SYNTAX							2 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_NO_ELEMENTS						3 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_INVALID_TOKEN					4 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_UNCLOSED_TOKEN					5 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_PARTIAL_CHAR					6 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_TAG_MISMATCH					7 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_DUPLICATE_ATTRIBUTE				8 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_JUNK_AFTER_DOC_ELEMENT			9 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_PARAM_ENTITY_REF				10 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_UNDEFINED_ENTITY				11 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_RECURSIVE_ENTITY_REF			12 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_ASYNC_ENTITY					13 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_BAD_CHAR_REF					14 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_BINARY_ENTITY_REF				15 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_ATTRIBUTE_EXTERNAL_ENTITY_REF	16 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_MISPLACED_EXPAT_PI				17 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_UNKNOWN_ENCODING				18 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_INCORRECT_ENCODING				19 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_UNCLOSED_CDATA_SECTION			20 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_EXTERNAL_ENTITY_HANDLING		21 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_NOT_STANDALONE					22 + EXPAT_ERROR_CODE;
#define EXPAT_ERROR_UNEXPECTED_STATE				23 + EXPAT_ERROR_CODE;

#endif







