# $Id: Makefile,v 1.3 2005/01/26 18:29:20 dmitryk Exp $

include $(IPDR_ROOT)/build/IPDR.defs

SIM = Simulators/IPDRsim # Simulators/HostSim
DEPENDENCIES = Exporter $(SIM)

include $(IPDR_ROOT)/build/IPDR.rules
