# $Id: Makefile,v 1.2 2004/12/13 17:28:52 dmitryk Exp $

include $(IPDR_ROOT)/build/IPDR.defs

SRC = TCPTransport.c

TARGET_TYPE = archive
TARGET_NAME = IPDRTCP

include $(IPDR_ROOT)/build/IPDR.rules
