#!/usr/bin/perl

# $Id: mibgen.pl,v 1.2 2005/04/21 11:30:21 dmitryk Exp $

# Automatically generate MIB constants from the CRANE MIB file.  A
# little post-processing (indentation) using Emacs is suggested; don't
# just blindly replace the contents of Client/ClientMIBConstants.c
# with what this program generates.

$var_name = "crane";

print "/* Automatically generated by mibgen.pl */\n";
print "\n";
print "#include <Common/ConfigurationHandler.h>\n";
print "#include <Common/ConfigurationNames.h>\n";
print "\n";
print "CRANE_Status ClientMIB_InitializeConstants(MIBHandler *MH)\n";
print "{\n";

while (<>) {
  if ( /([a-zA-Z]+)[ \t]*OBJECT-TYPE/) {
    $var_name = $1;
  } 
  else {
    if ( /([a-zA-Z]+)[ \t]*OBJECT IDENTIFIER/ ) {
      $var_name = $1;
    }  
    else {
      if ( /::=[ \t]*\{[ \t]*([a-zA-Z]+)[ \t]*([0-9]+)[ \t]*\}/ ) {
        print "  MIBHandler_DefineName(MH, \"", $var_name, "\", ", $2, ");\n" ;
        $var_name = "";
      }
    }
  }
}

print "  return CRANE_OK;\n";
print "}\n";
