#!/bin/ksh
# $Id: setTimes,v 1.2 2005/02/14 19:41:49 dmitryk Exp $

perl -e '$x = localtime(); print "time: ", time(), " ($x)\n"'

for arg in $* # e.g.: 192.168.8.88 192.168.9.87
do
  echo === $arg ===
  # the "$|" in the perl forces output non-buffered - very important
  perl -e '$|=1; sleep 1; print "time\nset_time @{[time()]}\n"; sleep 1' \
  | telnet $arg 40000
done

perl -e '$x = localtime(); print "time: ", time(), " ($x)\n"'
