#!/bin/ksh -e

# $Id: xlogs,v 1.1.1.1 2004/12/12 23:02:03 michaeld Exp $

# display all the various logs in one grand unified log

# suggested way of launching this:

# nohup xterm -e ./xlogs >/dev/null 2>&1 &

R=/opt/xacct
L=$R/Log
B=$R/bin
BIG=$L/big.log

$B/xacct_viewlog CEM 9 > $L/big_CEM.log 2>&1 &
$B/xacct_viewlog CUI 9 > $L/big_CUI.log 2>&1 &
$B/xacct_viewlog Gatherer 9 > $L/big_Gatherer.log 2>&1 &
$B/tailn \
'CEM       ' $L/big_CEM.log \
'CEM s     ' $L/CEM_stdout.log \
'CUI       ' $L/big_CUI.log \
'CUI s     ' $L/CUI_stdout.log \
'Gatherer  ' $L/big_Gatherer.log \
'Gatherer s' $L/Gatherer_stdout.log > $BIG 2>&1 &
sleep 1
exec tail -f $BIG
